name: Service - Build Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'service/**'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven Package
        working-directory: ./service
        run: ./mvnw -B package -DskipTests

      - name: Docker log in to Github Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from pom.xml file
        id: project
        uses: dostonhamrakulov/maven-artifact-version-extractor@v1.0
        with:
          file_path: ${{ github.workspace }}/service/pom.xml

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@a254f8ca60a858f3136a2f1f23a60969f2c402dd
        with:
          context: .
          file: ./service/src/main/docker/Dockerfile
          push: true
          tags: ghcr.io/sebastian-struecker/simple-feature-toggles/service:${{ steps.project.outputs.version }}
